# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: test biblio and build docker
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: test with Maven
        working-directory: projetDevOps
        run: mvn clean test
        
      # Add Docker build and run steps
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        working-directory: projetDevOps
        run: docker build -t samlops .

      - name: Run Docker image
        run: docker run samlops
        
      #Add generate-javadoc
      - name: Generate Javadoc
        working-directory: projetDevOps
        run: mvn clean package
        
      
      - name: Pages Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            working-directory: projetDevOps/docs
            
            enable_jekyll: false
            

