name: Jekyll Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true  # Necessary only if your site uses Git submodules

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Adjust according to the Ruby version defined in your Gemfile

    - name: Install dependencies
      working-directory: docs
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll site
      working-directory: docs
      run: |
        bundle exec jekyll build --trace  # '--trace' provides more verbose output to diagnose issues

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_site  # Ensure this path points to where your Jekyll build outputs the site files
