name: Build Jekyll Site

on:
  push:
    branches: [main, docs/**]  # Build Jekyll site when pushing to main or docs branches
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true  # Set this if your site uses submodules

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Set to the Ruby version your Jekyll site uses

    - name: Build and test
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # Set to your Jekyll site output directory
